volumes:
  gallerydb:
  image_repo:
    external: true

networks:
  doodle-gallery:
    driver: bridge

services:
  gallerydb:
    build:
      dockerfile: dockerfile.db
    networks:
      - doodle-gallery
    ports:
     - "8008:8008"
    volumes:
      - gallerydb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASS}
      - MYSQL_DATABASE=${SQL_DB}
  
  backend:
    build:
      context: ./backend
    networks:
      - doodle-gallery
    ports:
      - "8000:8000"
    volumes:
      - ${IMAGE_REPO_PATH}:/app/images
    depends_on:
      - gallerydb
    environment:
      - GALLERY_API_ACCESS_TOKEN=${GALLERY_API_ACCESS_TOKEN}
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASS}
      - MYSQL_DATABASE=${SQL_DB}
      - SQL_PASS=${SQL_PASS}
      - IMAGE_REPO_PATH=${IMAGE_REPO_PATH}
  
  frontend:
    image: nginx:latest
    networks:
      - doodle-gallery
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/frontend
    depends_on:
      - backend